### ISSUE TITLE
Db Initialisation

### ISSUE THREAD

**Issue by JonasHau** [LouisRichard/GameLibrary#2]
**Describe the bug**
The DB is created when the first user tries to register. So if you try login instead, you'll get a DbException saying to you that "The database connection miserably failed."

**To Reproduce**
1. Instal GameLibrary
2. Open it for the first time
3. Try logging in

**Expected behavior**
*TO DEFINE*

**Comment by LouisRichard** [comment]
**Expected behavior**
An exception that says *Please register first*.

This problem is already no more. This exception will probably not be used unless we find how to use it properly. 
The corrected version is currently in the branch `Sprint 4` and will be in the release of february (v1.0)
